name: Update APIMatic Portal and SDKs

on:
  push:
    branches:
      - main
    paths:
      - 'spec/**'
  workflow_dispatch:

jobs:
  update-portal:
    runs-on: ubuntu-latest

    env:
      APIMATIC_API_KEY: ${{ secrets.API_KEY }}
      APIMATIC_API_ID: ${{ secrets.API_ID }}
      GITHUB_REPO: your-github-repo-name
      GITHUB_ACCOUNT: your-github-account-name

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Install zip/unzip
        run: sudo apt-get install -y zip unzip

      - name: Zip spec directory
        run: zip -r portal-input.zip *
        working-directory: spec

      - name: List contents of zip (debug)
        run: zip -sf portal-input.zip
        working-directory: spec

      - name: Confirm OpenAPI file exists
        run: ls -l spec/

      - name: In-place spec import to APIMatic
        run: |
          curl -X PUT \
            --url "https://api.apimatic.io/api-entities/$APIMATIC_API_ID/import-via-file" \
            -H "user-agent: user-agent" \
            -H "Accept: application/vnd.apimatic.apiEntity.full.v1+json" \
            -H "Authorization: X-Auth-Key $APIMATIC_API_KEY" \
            -F "file=@spec/openapi-spec.json"


     