name: Update APIMatic Portal and SDKs

on:
  push:
    branches:
      - main
    paths:
      - 'spec/**'
  workflow_dispatch:

jobs:
  update-portal:
    runs-on: ubuntu-latest

    env:
      APIMATIC_API_KEY: ${{ secrets.API_KEY }}
      APIMATIC_API_ID: ${{ secrets.API_ENTITY_ID }}
     
      GH_PUSH_TOKEN: ${{ secrets.GH_PUSH_TOKEN }}
      TARGET_REPO: rehanalam/new-authlete-cs-sdk
      SDK_TEMPLATE: CS_NET_STANDARD_LIB

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Install zip/unzip
        run: sudo apt-get install -y zip unzip

      - name: Zip spec directory
        run: zip -r portal-input.zip *
        working-directory: spec

      - name: List contents of zip (debug)
        run: zip -sf portal-input.zip
        working-directory: spec

      - name: Confirm OpenAPI file exists
        run: ls -l spec/

      - name: In-place import with debug
        run: |
          curl -v -X PUT \
            --url "https://api.apimatic.io/api-entities/$APIMATIC_API_ID/import-via-file" \
            -H "user-agent: GitHub-Actions" \
            -H "Accept: application/vnd.apimatic.apiEntity.full.v1+json" \
            -H "Authorization: X-Auth-Key $APIMATIC_API_KEY" \
            -F "file=@spec/openapi-spec.json" \
            -o import-response.json

          echo "----- Response from APIMatic -----"
          cat import-response.json

      - name: Trigger SDK generation
        run: |
          curl -X POST \
            --url "https://api.apimatic.io/api-entities/$APIMATIC_API_ID/code-generations/generate" \
            -H "Accept: application/json" \
            -H "Authorization: X-Auth-Key $APIMATIC_API_KEY" \
            -d "template=$SDK_TEMPLATE" \
            -o sdk-gen-response.json

          cat sdk-gen-response.json
          echo "CODEGEN_ID=$(jq -r '.codeGenerationId' sdk-gen-response.json)" >> $GITHUB_ENV
      
      - name: Publish Developer Portal
        run: |
          curl -X PUT \
            --url "https://api.apimatic.io/api-entities/$APIMATIC_API_ID/hosted-portal" \
            -H "user-agent: GitHub-Actions" \
            -H "Authorization: X-Auth-Key $APIMATIC_API_KEY"

      - name: Wait for SDK generation to complete
        run: |
          echo "Waiting 10 seconds for SDK to be ready..."
          sleep 10
      
      - name: Download generated SDK
        run: |
          curl -X GET \
            -H "Authorization: X-Auth-Key $APIMATIC_API_KEY" \
            --output sdk.zip \
            "https://api.apimatic.io/api-entities/$APIMATIC_API_ID/code-generations/688901f8a41170377a2f5461/generated-sdk"

      - name: Unzip SDK
        run: unzip sdk.zip -d sdk

      - name: Clone target repo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git clone https://x-access-token:$GH_PUSH_TOKEN@github.com/$TARGET_REPO.git target-repo

      - name: Copy SDK to repo
        run: |
          rm -rf target-repo/*
          cp -r sdk/* target-repo/

      - name: Push to GitHub
        run: |
          cd target-repo
          git add .
          git commit -m "chore: auto-update SDK $(date +%Y-%m-%d)"
          git push origin main



     