name: Update Portal

on:
  push:
    branches:
      - main
    paths:
      - 'spec/**'
  workflow_dispatch:

jobs:
  update-portal:
    runs-on: ubuntu-latest

    env:
      APIMATIC_API_KEY: ${{ secrets.APIMATIC_API_KEY }}
      APIMATIC_API_ID: ${{ secrets.APIMATIC_API_ID }}
      GITHUB_REPO: your-GitHub-repo-name
      GITHUB_ACCOUNT: your-github-account-name

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Install zip/unzip
        run: sudo apt-get install -y zip unzip

      - name: Zip spec and portal files
        run: zip -r portal-input.zip *
        working-directory: spec

      - name: List contents of zip
        run: zip -sf portal-input.zip
        working-directory: spec

      - name: In-place spec import to APIMatic
        run: |
          curl -X PUT \
            --url "https://www.apimatic.io/api/api-entities/$APIMATIC_API_ID" \
            -H "Authorization: X-Auth-Key $APIMATIC_API_KEY" \
            -H "Accept: application/json" \
            -F "file=@spec/openapi-spec.json" \
            -o entity.json

      - name: Trigger SDK generation
        run: |
          curl -X POST \
            --url "https://www.apimatic.io/api/api-entities/$APIMATIC_API_ID/code-generations" \
            -H "Authorization: X-Auth-Key $APIMATIC_API_KEY" \
            -H "accept: application/json, text/plain, */*" \
            -H "content-type: application/json;charset=UTF-8" \
            --data-raw '{
              "template": "CS_NET_STANDARD_LIB",
              "repoName": "'"$GITHUB_REPO"'",
              "branchName": "CodeGen-CS",
              "commitMessage": "spec updated",
              "accountName": "'"$GITHUB_ACCOUNT"'"
            }' \
            --compressed
